### ISSUE TITLE
ppa.launchpad does not have a Release file

### ISSUE THREAD

**Issue by kberisha42** [xflux-gui/fluxgui#105]
Hi,
I am currently having an issue trying to install flux on my debian stretch.
When I follow these instructions : https://github.com/xflux-gui/fluxgui/blob/master/README.md
and I run apt-get update, I always get the following output:

`
W: The repository 'http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu cosmic Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'http://deb.playonlinux.com stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu/dists/cosmic/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.`

So I tried to run the manual install as described below in the README, but when I run fluxgui, I get this:

`(fluxgui:2886): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
No D-BUS daemon running

Critical error. Exiting.
Traceback (most recent call last):
  File "/usr/local/bin/fluxgui", line 20, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 213, in main
    app = FluxGUI()
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 28, in __init__
    self.exit(1)
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 43, in exit
    self.xflux_controller.stop()
AttributeError: 'FluxGUI' object has no attribute 'xflux_controller'
Exception AttributeError: AttributeError("'FluxGUI' object has no attribute 'xflux_controller'",) in <bound method FluxGUI.__del__ of <fluxgui.fluxapp.FluxGUI object at 0x7fa755b0f710>> ignored`

Thanks for your help :)

**Comment by chriskuech** [comment]
Observed on Ubuntu 18.10

**Comment by ntc2** [comment]
The PPA is maintained by @NHellFire, maybe he can do something about the `Release` file? But I don't have any control over that, sorry.

As to the other error, I just merged a PR (#112) that ports fluxgui to Python 3 and GTK+ 3, so hopefully that will solve your other problem. Please open a separate issue about that problem if it persists when you install the new version.

**Comment by NHellFire** [comment]
Seems my PPA uploads have been silently discarded by Launchpad for months, I've contacted support and awaiting a response.
