### ISSUE TITLE
Custom Time Range?

### ISSUE THREAD

**Issue by arya001** [xflux-gui/fluxgui#106]
Hi,

I installed fluxgui via PPA on Ubuntu Xenial. I would like to know if I can set a custom time range like the NightShift on iPhone

**Comment by ntc2** [comment]
Setting a custom time range is not supported, but if you would like to implement it I would be happy to accept a PR.

**Comment by allanlaal** [comment]
I (and most northern europeans) have the same need. in midJune there isnt a sunset/sunrise time :D
