### ISSUE TITLE
PPA Throws unable to resolve false

### ISSUE THREAD

**Issue by digitalsparky** [xflux-gui/fluxgui#108]
Setting up fluxgui (1:1.1.11~pre~20171222-gf22fdbf-1~bionic) ...

Downloading xflux...
--2018-11-22 19:04:05--  https://justgetflux.com/linux/xflux64.tgz
Resolving false (false)... failed: Name or service not known.
wget: unable to resolve host address 'false’

Download failed
fluxgui is NOT installed.
dpkg: error processing package fluxgui (--configure):
 installed fluxgui package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 fluxgui
E: Sub-process /usr/bin/dpkg returned an error code (1)

Looks like the wget is trying to get something it shouldn't, or there's an argument/variable there that isn't being validated.

**Comment by ntc2** [comment]
Closed by #109 (altho I didn't test).
