### ISSUE TITLE
Add a Redshift backend to fluxgui (or abandon the project!)

### ISSUE THREAD

**Issue by ntc2** [xflux-gui/fluxgui#113]
There's been no progress on #27 for two years, and now `xflux` doesn't work on either of the computers I (the `fluxgui` maintainer) use regularly. On the other hand, `redshift-gtk` works great on both those computers. So, I'm thinking that either `fluxgui` should be abandoned until `xflux` is fixed, or we should add a [Redshift](http://jonls.dk/redshift/) backend.

Is there some benefit to continuing this project when there is a viable alternative in `redshift-gtk`, and seemingly no future for `xflux`?

Thoughts? Pull requests?

**Comment by LaBatata101** [comment]
It seems like a good idea to add a redshift backend.

**Comment by Kilian** [comment]
This is probably the right thing to do indeed.

**Comment by black-snow** [comment]
So flux isn't working currently?

**Comment by jcklpe** [comment]
I tried installing this, and it didn't seem to work, but I tried redshift and it did. Would love a flux like GUI though to control redshift so consider me supportive of this move.

**Comment by dandv** [comment]
Redshift had extremely few options. There's no way to control the start of the dimming even, let alone the color temperature.

**Comment by ntc2** [comment]
> Redshift had extremely few options. There's no way to control the start of the dimming even, let alone the color temperature.

Redshift does actually let you control the day and night color temps, via the config file `~/.config/redshift.conf`. For example, here is my config:
```
; See https://wiki.archlinux.org/index.php/redshift#Configuration.
;
; To make redshift autostart on boot, run `redshift-gtk` manually
; once, click on the icon, and choose "autostart". The autostart file
; appears in `~/.config/autostart/redshift-gtk.desktop`.

; Global settings for redshift
[redshift]
; Set the day and night screen temperatures (Neutral is 6500K)
temp-day=4200
temp-night=2500

; Provide the lat/lon myself.
location-provider=manual

; The location provider config.
[manual]
; Portland.
;lat=45.52
;lon=-122.68
; Berawa
lat=-8.660500
lon=115.146764
```

**Comment by FilthyChef** [comment]
What I also very like about Windows f.lux and find lacking on Linux in both Redshift and f.lux implementation is automatic "disable for fullscreen apps" and an option to select specific apps that also disable f.lux when are in window focus. It's annoying to remember to press a hotkey each time I need true color representation.

Otherwise I never needed Philips light controls, extra effects or Daytime/Sunset/Bedtime color controls because I set it to 4200K / 24hours
