### ISSUE TITLE
Any plans for a new stable release?

### ISSUE THREAD

**Issue by ConiKost** [xflux-gui/fluxgui#119]
Are there any plans to do a new stable release, since there were a lot of changed, including python3 support, after the last stable released.

**Comment by ntc2** [comment]
Yes, that's a good idea.

**Comment by ConiKost** [comment]
Cool, would be nice :)

**Comment by ntc2** [comment]
Done https://github.com/xflux-gui/fluxgui/releases/tag/v1.2.0

**Comment by ConiKost** [comment]
Thanks! :)
