### ISSUE TITLE
f.lux indicator applet doesn't run - preferences screen keeps closing

### ISSUE THREAD

**Issue by hideraimu** [xflux-gui/fluxgui#120]
After installing and opening it, it gives the message "The f.lux indicator applet needs to know your latitude and zipcode to run. Please fill either of them in on the preferences screen and click 'Close'." Thing is, I can't click or type anything in the preferences screen because when I click OK to close the message box, the preferences screen goes away too.

**Comment by jreindel** [comment]
I am having the same issue.
I did manual install onto Ubuntu 18.04. Manual because of arm64 architecture.
I uninstalled and reinstalled to make sure I didnt see anything fail in the process.

I open by typing flexgui into terminal. 
same error as pf71fs. I click ok, and the preferences window goes away. I can see the defaults in the preferences window if I drag the warning message away. After it all closes terminal says:

`[Errno 8] Exec format error`
`Critical error. Exiting.`
` `
`(fluxgui:18344): Gtk-CRITICAL **: 21:00:25.482: gtk_main_quit: assertion 'main_loops != NULL' failed`

**Comment by ntc2** [comment]
Does the `xflux` program itself work on your systems? See #27 for how to test.

**Comment by ERasnier** [comment]
Same error. I'm using a Raspberry Pi B 8 gig ram armhf processor.

Running through cli gives this.
```
/home/pi/.local/lib/python3.7/site-packages/fluxgui/fluxapp.py:3: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk as gtk
/home/pi/.local/lib/python3.7/site-packages/fluxgui/fluxapp.py:4: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as appindicator
```

After opening then...
```
(fluxgui:16321): Gdk-CRITICAL **: 00:19:35.779: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
[Errno 8] Exec format error
Critical error. Exiting.

(fluxgui:16321): Gtk-CRITICAL **: 00:19:50.730: gtk_main_quit: assertion 'main_loops != NULL' failed
```

After pressing ok at the pop up.

Doing the #27 gives:

`bash: /usr/local/bin/xflux: cannot execute binary file: Exec format error`
And it's the same with xflux11 and 12 binary.

I'm also having trouble with Redshift which does work but the same issue of no colour change happens.

**Comment by ntc2** [comment]
> Same error. I'm using a Raspberry Pi B 8 gig ram armhf processor.

I'm afraid `xflux` only runs on x86, not arm.

> Doing the #27 gives:
> 
> `bash: /usr/local/bin/xflux: cannot execute binary file: Exec format error`
> And it's the same with xflux11 and 12 binary.

Yeah, this is telling you that the xflux binary is not compatible with your processor.
