### ISSUE TITLE
can't add repo on ubuntu 19.04

### ISSUE THREAD

**Issue by superbonaci** [xflux-gui/fluxgui#123]
```
root@user:~# sudo add-apt-repository ppa:nathan-renniewaldock/flux
 GUI for f.lux
https://justgetflux.com/

Bugs/feature requests should be directed to: https://github.com/xflux-gui/xflux-gui
I do not develop this, only provide a PPA.
 More info: https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://archive.ubuntu.com/ubuntu disco InRelease
Get:2 http://archive.ubuntu.com/ubuntu disco-updates InRelease [97,5 kB]                                                                                                                 
Hit:3 https://dl.winehq.org/wine-builds/ubuntu disco InRelease                                                                                                                              
Hit:4 http://ppa.launchpad.net/lutris-team/lutris/ubuntu disco InRelease                                                                                                                    
Get:5 http://security.ubuntu.com/ubuntu disco-security InRelease [97,5 kB]                                                                                                                  
Ign:6 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                
Hit:7 https://deb.opera.com/opera-stable stable InRelease                                                                                                                                   
Get:8 http://archive.ubuntu.com/ubuntu disco-backports InRelease [88,8 kB]                                                                                                               
Ign:9 http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu disco InRelease                                                        
Hit:10 http://dl.google.com/linux/chrome/deb stable Release                                                                      
Hit:11 http://archive.canonical.com/ubuntu disco InRelease                                                                       
Err:12 http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu disco Release
  404  Not Found [IP: xx.xxx.xx.xx 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by abejaranoh** [comment]
There is no folder for disco 
http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu/dists/

**Comment by victortostes-hotmart** [comment]
+1 :upside_down_face:

**Comment by VitaliyKuznetsov** [comment]
You can make a file in /etc/apt/sources.list.d/ (for example you can name it nathan-renniewaldock-ubuntu-flux-cosmic.list) and add inside a text:
`deb http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu bionic main `
`deb-src http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu bionic main `
This is work really fine for my cosmic (19.04) install but **i cant recommend solve problem by that way**. Maybe manual install will be better solution

**Comment by jclaveau** [comment]
> sudo nano /etc/apt/sources.list.d/nathan-renniewaldock-ubuntu-flux-disco.list

Adding trusted option fixes the unsecure issue

> deb [trusted=yes] http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu disco main

But the apt update gives
> http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu/dists/disco/main/binary-amd64/Packages  404  Not Found [IP : 91.189.95.83 80]

**Comment by abejaranoh** [comment]
well... there is no folder with the packages for Disco. and the latest upate is from 2017

**Comment by ntc2** [comment]
The PPA is maintained by @NHellFire . Perhaps he can help?

**Comment by superbonaci** [comment]
Can't you add a repo within github?

**Comment by abejaranoh** [comment]
can I set a ppa too? is there any guide?

**Comment by superbonaci** [comment]
I'm not on ubuntu 19.04

**Comment by abejaranoh** [comment]
Folders with packages for bionic (18.04), disco (19.04), eoan (19.10) are on the ppa... please test

**Comment by NHellFire** [comment]
Launchpad had an issue with not accepting my uploads, it's since been fixed and there should be (reasonably) up-to-date packages for all supported Ubuntu releases.

**Comment by abejaranoh** [comment]
i dont get it... i just tested it on ubuntu 19.04 and it works.

**Comment by mwilson-cb** [comment]
Added, tested, and working for me on 19.10.

**Comment by Minabsapi** [comment]
I confirm it works on Ubuntu 19.04 as well now.

**Comment by Domminique** [comment]
Had the same while installing Docker on my Ubuntu focal workstation, 
I solve by removing the ppa causing the error

**sudo add-apt-repository -r ppa:nathan-renniewaldock/flux**

**Comment by superbonaci** [comment]
@Domminique thanks that's it. Luckily when I upgraded from 19.10 to 20.04 all additional repos get disabled, so didn't experience the issue anymore.
