### ISSUE TITLE
Make 'gschemas.compiled' optional

### ISSUE THREAD

**Issue by ConiKost** [xflux-gui/fluxgui#124]
Currently, ```setup.py``` compiles and installs always ```gschemas.compiled```. This is on most distros fine, but on source distros like Gentoo, this is a problem, since Gentoo compiles the gschema by it's own. Could be introduce a parameter, for optionally disabling this?

**Comment by ntc2** [comment]
OK, would you like to submit a PR?

**Comment by ConiKost** [comment]
Have a look, pushed a PR. I am not an expert in python stuff..

**Comment by ntc2** [comment]
Thanks for the PR; merged!
