### ISSUE TITLE
Doesnt work on Raspberry pi 4

### ISSUE THREAD

**Issue by rusikf** [xflux-gui/fluxgui#127]
Hi fluxgui geeks, how to run it on raspberry pi 4 ? ( Raspbian OS) ( I installed it manually like on README described)

```
pi@raspberrypi:~ $ fluxgui

(fluxgui:1955): Gdk-CRITICAL **: 08:39:19.863: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
[Errno 8] Exec format error
Critical error. Exiting.

(fluxgui:1955): Gtk-CRITICAL **: 08:39:21.594: gtk_main_quit: assertion 'main_loops != NULL' failed
```

**Comment by evanlesmez** [comment]
^ Same problem for me as above. The gui pops up but warns that no latitude or longitude can be gathered and when you close that popup the app crashes.

**Comment by ntc2** [comment]
Does the underlying `xflux` program work on Raspberry Pi 4? See #27 for how to test.

**Comment by kannaiah** [comment]
On RPI 4 I'm seeing this, 

```
file /usr/local/bin/xflux
/usr/local/bin/xflux: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=8c600be0a4671d1d4b65189209523525c234aee3, not stripped
```
It looks like install just checks for bitness and not arch.

**Comment by ntc2** [comment]
Oh, I didn't know Raspberry Pi was ARM. I believe the `xflux` binary is only available for x86, so we're out of luck.
