### ISSUE TITLE
where's the scrolling bar mentioned in this link?

### ISSUE THREAD

**Issue by appleyuchi** [xflux-gui/fluxgui#131]
I have install the bionic edtion of fluxgui
But my gui is:

![image](https://user-images.githubusercontent.com/27613483/69871880-eadba100-12ee-11ea-8229-5ee650c757ae.png)

what I want to get is the gui with scrolling bar in this link:
https://www.ubuntupit.com/10-best-eye-care-software-for-linux-to-protect-your-eyes/

![1111111111](https://user-images.githubusercontent.com/27613483/69872026-50c82880-12ef-11ea-8947-22cc9d1e0c12.jpg)

Could anyone tell me how to get the scrolling bar?
Thanks

**Comment by ntc2** [comment]
That screenshot appears to be from the flux homepage --
https://justgetflux.com/ -- and it must be the GUI for flux on a different
platform. The Linux flux GUI doesn't look like that. Sorry :/

Also, flux doesn't work on many newer Linux distros, so you might want to
try RedShift instead.

**Comment by appleyuchi** [comment]
Got it,thanks~
Could you  develop the scrolling bar for linux please?
Much Thanks~
