### ISSUE TITLE
Flux overrides xrandr/brightness-controller settings

### ISSUE THREAD

**Issue by daniel-gomes** [xflux-gui/fluxgui#132]
When setting eg. an external display's brightness via `xrandr` or `brightness-controller`, the new settings gets immediately reset to the original value. Stopping `flux` before doing that will eliminate the problem.

Using `fluxgui 1.2.0` from the PPA and Ubuntu 18.

**Comment by ntc2** [comment]
Is this not the expected behavior?

**Comment by Ev1lbl0w** [comment]
> Is this not the expected behavior?

I don't think so; flux only changes the color temperature of the screen, it should not enforce a brightness level.

I also face this issue and it's annoying, as I tone down my screen brightness in the morning to be easy in the eyes. But for that, I have to close `xflux`.

**Comment by ntc2** [comment]
This sounds like an issue with `xflux` itself, which is not part of this project. Here we just maintain a GUI frontend for `xflux`.
