### ISSUE TITLE
mention that flux is not open source

### ISSUE THREAD

**Issue by baptx** [xflux-gui/fluxgui#133]
I read that flux is not open source. However this repository is confusing by saying "Open source GUI for xflux". It would be nice to mention that the xflux daemon is not open source. Usually I only install open source software to prevent spyware but I installed this app by mistake since it was misleading.
If someone has a suggestion for an open source alternative, it would be nice also.

**Comment by douglasg14b** [comment]
@baptx Redshift?

**Comment by baptx** [comment]
@douglasg14b thanks, I heard of it some times ago. I will try it later.
