### ISSUE TITLE
controlling bar is needed,thanks

### ISSUE THREAD

**Issue by appleyuchi** [xflux-gui/fluxgui#134]
Hi,thanks for your work first~

And..... I want a "controlling bar"which can control how dark/Bright it is.
Just like this:

![护眼需求](https://user-images.githubusercontent.com/27613483/75774358-cdedb880-5d8a-11ea-9be4-9a19990e25f8.png)

But the software in the picture needs wine(a windows emulator).

So could you develop a controlling bar ?

**Comment by ntc2** [comment]
Unfortunately `xflux`, the program that actually changes the screen color, is no longer maintained. And it's closed source. So, I consider this GUI project to be in maintenance mode. I suggest trying RedShift instead: http://jonls.dk/redshift/.
