### ISSUE TITLE
ModuleNotFoundError: No module named 'pexpect'

### ISSUE THREAD

**Issue by FireFingertips** [xflux-gui/fluxgui#136]
For some reason, repositories on my linux refuse to work (not only with f.lux), and I know near to nothing about linux ( I downloaded it to bring my slow laptop life and be more useful to me).

So I will just post this screenshot (This is after installing it manually).
![image](https://user-images.githubusercontent.com/41827788/80785856-9d06e580-8b79-11ea-84d1-18cbd7f80102.png)

**Comment by ntc2** [comment]
Looks like you need to install the Python pexpect package. I'll update the Readme ...
