### ISSUE TITLE
fluxgui doesn't have a module named fluxgui (?)

### ISSUE THREAD

**Issue by mkstarr** [xflux-gui/fluxgui#137]
$ ./fluxgui 
Traceback (most recent call last):
  File "./fluxgui", line 17, in < module >
    from fluxgui.fluxapp import main
ModuleNotFoundError: No module named 'fluxgui'

**Comment by ntc2** [comment]
You haven't provided enough info here to get help: what system are you using? How did you install fluxgui?

But it probably won't work anyway: see Issue #27 for how to check if the underlying `xflux` program works on your system -- probably doesn't -- and then worry about installing fluxgui.
