### ISSUE TITLE
Unable to locate package fluxgui

### ISSUE THREAD

**Issue by AeShevch** [xflux-gui/fluxgui#142]
sudo add-apt-repository ppa:nathan-renniewaldock/flux
sudo apt-get update
sudo apt-get install fluxgui

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package fluxgui

**Comment by abejaranoh** [comment]
are you using ubuntu 20.04? 
https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux
