### ISSUE TITLE
PPA won't install on Linux Mint 21: PPA does not support jammy

### ISSUE THREAD

**Issue by Free-Radical** [xflux-gui/fluxgui#153]
`$ sudo add-apt-repository ppa:nathan-renniewaldock/flux' 
'[sudo] password for user0:' 
'Cannot add PPA: ''This PPA does not support jammy''`

**Comment by ntc2** [comment]
The PPA hasn't been updated since 2019 -- and it's not maintained by me -- so I don't think this is going to happen: https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux

**Comment by abejaranoh** [comment]
@NHellFire do you know if there any other / updated PPA for this package?
