### ISSUE TITLE
flux not working on ubunto 22

### ISSUE THREAD

**Issue by assohail** [xflux-gui/fluxgui#154]

**Comment by assohail** [comment]
A lot of developers having difficulties to install flux on latest versions
When installing through cmd always gives the same error
Unable to locate package fluxgui

![Screenshot from 2022-09-23 17-02-32](https://user-images.githubusercontent.com/40453975/191956462-559098e0-b3d6-4fc0-8bad-82200352d389.png)

**Comment by ntc2** [comment]
The PPA hasn't been updated since 2019 -- and it's not maintained by me -- so I don't think this is going to happen: https://launchpad.net/~nathan-renniewaldock/+archive/ubuntu/flux
