### ISSUE TITLE
I managed to fix a problem installing f.lux with Mx Linux

### ISSUE THREAD

**Issue by magnum233** [xflux-gui/fluxgui#159]
Hi im using MX Linux version 21.3 AHS.  following the instructions in the wiki for the manual install after installing the partial Ubuntu/Debian dependencies it hit an error upon launching fluxgui

$ sudo fluxgui
Traceback (most recent call last):
  File "/usr/local/bin/fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
  File "/usr/local/lib/python3.9/dist-packages/fluxgui/fluxapp.py", line 6, in <module>
    import fluxgui.settings as settings
  File "/usr/local/lib/python3.9/dist-packages/fluxgui/settings/__init__.py", line 3, in <module>
    from xdg.DesktopEntry import DesktopEntry
ModuleNotFoundError: No module named 'xdg'

after a short google i was able to find a solution
https://askubuntu.com/questions/701045/redshift-gtk-crashes-on-start-importerror-no-module-named-xdg
Whilst not exactly the same error the following solution provided a partial fix enough to launch and use the app

answered Nov 22, 2015 at 8:37
Martin Ueding
'You are missing a Python dependency. Install it with sudo apt-get install python3-xdg. I [just checked](http://packages.ubuntu.com/wily/python3-xdg), it is included in Ubuntu Wily. If it is not included in your version of Linux Mint, you can install it by downloading it from the [mentioned site](http://packages.ubuntu.com/wily/python3-xdg) and installing it with sudo dpkg -i … manually.'

After launching in terminal with the installed missing dependency it displays
$ sudo fluxgui
Failed to import plain appindicator ...
Starting backend app: ['xflux', '-l', '-41.254990', '-g', '174.935690', '-k', '3400', '-nofork']

(fluxgui:8914): Gdk-CRITICAL **: 21:31:11.218: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Maybe another dependency is missing? not sure but the app is working well enough.  I thought i'd share this with anyone that was having trouble getting it to work in Debian based distro's.

**Comment by abejaranoh** [comment]
Hallo,

at least in Debian 10 (buster) and Ubuntu 22.04 it is included: 

https://packages.debian.org/buster/python3-xdg
https://packages.ubuntu.com/jammy/python3-xdg

Maybe a dependency  check would be the place but I just dont know where it is :D

**Comment by ntc2** [comment]
The `python3-xdg` dep was in the `debian/control` (deps spec for the Debian package), but the README only mentioned `python-xdg` in the old Python 2 deps. I just updated the README in 91ef659.

The import failure message in

    $ sudo fluxgui
    Failed to import plain appindicator ...

was a buggy diagnostic; the failure didn't matter. I just fixed that in a21f55f.

Thanks!
