### ISSUE TITLE
Feature request: Tests?

### ISSUE THREAD

**Issue by jgarte** [xflux-gui/fluxgui#161]
Hi,

Would you welcome PRs for a test suite?

**Comment by ntc2** [comment]
Probably, but what do you have in mind?

**Comment by jgarte** [comment]
I was thinking of providing unit tests to get started. For example, unit testing code like this:

https://github.com/xflux-gui/fluxgui/blob/master/src/fluxgui/settings/__init__.py#L46

I would have to compile a list of things to test in the code base. I was thinking of using pytest.

**Comment by ntc2** [comment]
OK. I don't think this would be super useful, but it wouldn't hurt either. So if you have time for this, go ahead.

Perhaps more useful would be some kind of integration tests that test interaction between the GUI and the backends, but I have no idea how to go about this, and expect it would be quite involved. E.g. it might involve creating a third backend, a mockup backend for testing, and some kind of GUI test automation (no idea how that works).
