### ISSUE TITLE
Missing apps.fluxgui settings schema after manual install with setup.py

### ISSUE THREAD

**Issue by neomachiney** [xflux-gui/fluxgui#169]
fluxgui
/usr/local/bin/fluxgui:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('f.lux-indicator-applet==2.0.1rc0', 'fluxgui')

(fluxgui:37651): GLib-GIO-ERROR **: 03:13:50.553: Settings schema 'apps.fluxgui' is not installed
Trace/breakpoint trap

**Comment by ntc2** [comment]
I wonder if you need to run `glib-compile-schemas` manually? There's an example in the "uninstall" section: https://github.com/xflux-gui/fluxgui#manual-uninstall. Don't do the `xargs rm` part, just the `glib-compile-schemas` part.

Let me know if that helps.

**Comment by neomachiney** [comment]
@ntc2 
```
root@kali-linux:/tmp/fluxgui# ./fluxgui 
Traceback (most recent call last):
  File "/tmp/fluxgui/./fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
ModuleNotFoundError: No module named 'fluxgui'
root@kali-linux:/tmp/fluxgui# sudo glib-compile-schemas "$(dirname "$(grep apps.fluxgui.gschema.xml installed.txt)")"
root@kali-linux:/tmp/fluxgui# ./f
fluxgui                          f.lux_indicator_applet.egg-info/ 
root@kali-linux:/tmp/fluxgui# ./fluxgui 
Traceback (most recent call last):
  File "/tmp/fluxgui/./fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
ModuleNotFoundError: No module named 'fluxgui'
```
Redshift works. Is there any cli for f.lux. Any idea whats going wrong?

**Comment by ntc2** [comment]
Looks like you're having a different problem now that is unrelated to your first problem, since it appears to be happening earlier: i.e. `fluxgui` can't even load its deps now. To clarify, you're not supposed to uninstall, just run the `glib-compile-schemas ...` command that you ran, after installing.

The CLI for flux is the `xflux` binary.

**Comment by neomachiney** [comment]
Ok xflux is working. I tried glib-compile-schemas without any rm commands. It doesnt look to do anything

**Comment by ntc2** [comment]
One thing I notice is that you're running `./fluxgui`, not `fluxgui` (no `./`). I think you want the second version, which runs the `fluxgui` script you installed. If you want to do the first version, which is running the local version from the repo, then you need to do it like this:

https://github.com/xflux-gui/fluxgui#running-fluxgui-without-installing

**Comment by neomachiney** [comment]
![image](https://github.com/xflux-gui/fluxgui/assets/118899053/21c44268-4d03-4355-98c7-4ca0500efe47)
Ok at least GUI is working now 
![image](https://github.com/xflux-gui/fluxgui/assets/118899053/e5035cda-dcdd-4b38-9063-74e80194c607)
