### ISSUE TITLE
Hotkeys akin to the Windows Flux install

### ISSUE THREAD

**Issue by n5corp** [xflux-gui/fluxgui#17]
As it says, I'd like a quick way at dimming the screen no matter the state of the color temperature.  

If this is the wrong place for this, please direct me.

**Comment by ntc2** [comment]
I don't understand the difference between "dimming the screen" and "color temperature" here. Flux adjusts the "color temperature" and the screen brightness is controlled separately (e.g. by pressing brightness adjustment buttons if you have a laptop, or via buttons on your monitor if you have an LCD). Are you asking for a shortcut to adjust the *color temperature*?

**Comment by n5corp** [comment]
I suppose brightness adjustment as my monitor has no dedicated buttons.
I'm asking for the option to turn down the brightness while not necessarily
changing the color temperature, it's really the only thing from the Windows
version I'm missing.

**Comment by serkazak** [comment]
I am unaware of such functionality but is it possible to send ddc commands to monitor to adjust brightness (or if possible color temperature or gamma etc.). It would be great if flux could trigger ddccontrol or ddctool to send such functions to the monitor through DDC/CI. I decrease the brightness setting when flux activates at night and then in the morning i have to increase it again.

**Comment by itsabear** [comment]
For summary: brightness settings adjustment need to be implemented for Windows Flux?

**Comment by ntc2** [comment]
Closing this as I doubt anyone will be implementing this anytime soon. Here's a SO page about using DDC to control monitor brightness: https://askubuntu.com/questions/218993/how-to-change-external-monitor-brightness-via-ddc-ic.
