### ISSUE TITLE
Can't run fluxgui after installing on Linux Mint

### ISSUE THREAD

**Issue by yoyo662** [xflux-gui/fluxgui#173]
I followed the following instructions and everything seemed to work fine :

cd /tmp
git clone "https://github.com/xflux-gui/fluxgui.git"
cd fluxgui
./download-xflux.py

But when I type "fluxgui" to run the program, it says "fluxgui: command not found"

**Comment by ntc2** [comment]
That's not the whole installation process. Did you run all the steps as described [here](https://github.com/xflux-gui/fluxgui?tab=readme-ov-file#manual-install), and update your `PATH` has necessary?

**Comment by yoyo662** [comment]
I did in fact miss something. I must have been a bit confused when I was installing this. Sorry.
