### ISSUE TITLE
failed to import Atayan 

### ISSUE THREAD

**Issue by aragon5956** [xflux-gui/fluxgui#176]
hello , 
i've this problem : 
`(env) alexandre@alexandre-Matebook:~/Documents/fluxgui$ ./fluxgui 
Failed to import Ayatana appindicator, falling back to plain appindicator ...
Failed to import plain appindicator ...
Failed to import an appindicator implementation, dying ...
(env) alexandre@alexandre-Matebook:~/Documents/fluxgui$ 
`
could you help me.
i have this error , after  thieses commands : 

`(env) alexandre@alexandre-Matebook:~/Documents/fluxgui$ deactivate
rm -rf env
python3 -m venv env --system-site-packages
source env/bin/activate
pip install -e .

DEPRECATION: Loading egg at /home/alexandre/.local/lib/python3.12/site-packages/f.lux_indicator_applet-2.0.1rc1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Obtaining file:///home/alexandre/Documents/fluxgui
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: f.lux-indicator-applet
  Building editable for f.lux-indicator-applet (pyproject.toml) ... done
  Created wheel for f.lux-indicator-applet: filename=f.lux_indicator_applet-2.0.1rc1-0.editable-py3-none-any.whl size=4762 sha256=c76fc2dcf7741680d29d2c590aae93cc5655392ab87b0ed5145c8835e4b471af
  Stored in directory: /tmp/pip-ephem-wheel-cache-xqun04qd/wheels/7a/09/1e/f5e27e2f4dac5cd9a9eb66cfc5c73327dafbc5036b6520e47b
Successfully built f.lux-indicator-applet
Installing collected packages: f.lux-indicator-applet
  Attempting uninstall: f.lux-indicator-applet
    Found existing installation: f.lux-indicator-applet 2.0.1rc1
    Not uninstalling f-lux-indicator-applet at /home/alexandre/Documents/fluxgui, outside environment /home/alexandre/Documents/fluxgui/env
    Can't uninstall 'f.lux-indicator-applet'. No files were found to uninstall.
Successfully installed f.lux-indicator-applet-2.0.1rc1
(env) alexandre@alexandre-Matebook:~/Documents/fluxgui$ 
(env) alexandre@alexandre-Matebook:~/Documents/fluxgui$ ./fluxgui 
Failed to import Ayatana appindicator, falling back to plain appindicator ...
Failed to import plain appindicator ...
Failed to import an appindicator implementation, dying ...
(env) alexandre@alexandre-Matebook:~/Documents/fluxgui$ 

`

**Comment by aragon5956** [comment]
for my ubuntu 24.0 et 6.8 generic kernel  version, i've theses solutions : 

`sudo apt-get install gir1.2-appindicator3-0.1 gir1.2-ayatanaappindicator3-0.1
sudo apt-get install python3-gi python3-gi-cairo gir1.2-gtk-3.0
`

and then compiling the files: 

`glib-compile-schemas .
`
for compiling all XML schemas files, see [https://manpages.debian.org/bullseye/libglib2.0-bin/glib-compile-schemas.1.en.html](url)
and then : 
`sudo apt-get install redshift
`

**Comment by ntc2** [comment]
So it sounds like you solved the problem! I added your additional apt deps to the README ...
