### ISSUE TITLE
xfluxgui doesn't work

### ISSUE THREAD

**Issue by aragon5956** [xflux-gui/fluxgui#177]
hello, 
i have the software xfluxgui which doesn't work, why ?
if I enter the parameters it does not change anything to do 

[Capture vidéo du 2024-08-19 02-17-01.webm](https://github.com/user-attachments/assets/e4255569-826a-44f0-bef4-2b2aae089182)

my information : 

`alexandre@alexandre-Matebook:~/Documents/fluxgui$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble
alexandre@alexandre-Matebook:~/Documents/fluxgui$ uname -r
6.8.0-40-generic
alexandre@alexandre-Matebook:~/Documents/fluxgui$ 
`
could you help me ?

**Comment by ntc2** [comment]
You appear to be using the `xflux` backend. It's broken on most systems since ~2016. See #27.
