### ISSUE TITLE
Movie mode

### ISSUE THREAD

**Issue by theblackhole** [xflux-gui/fluxgui#36]
I think it would be nice to have a movie mode on linux too. :smiley: 

> **How long is Movie Mode and what does it do?**
> It's 2½ hours. We designed Movie Mode to preserve sky colors and shadow detail, while still providing a warmer color tone. It's not perfect on either count, but it strikes a balance.
> ([Flux F.A.Q](https://justgetflux.com/faq.html))

**Comment by Kilian** [comment]
pinging @herf :)

**Comment by ntc2** [comment]
Marking this "won't fix" since it's an `xflux` feature and thus out of our control. Also, given how long Issue #27 has been around (also an `xflux` issue), it seems `xflux` is not actively maintained anymore.
