### ISSUE TITLE
Make it as snap package

### ISSUE THREAD

**Issue by unigazer** [xflux-gui/fluxgui#54]
Hello. 

Would you consider making f.lux as snap package so that it can be installed on any Linux distro? 
I've also heard that starting from 18.04, Ubuntu will be "all snap" packages instead of current .deb packages.

https://snapcraft.io/

**Comment by mkg20001** [comment]
https://github.com/mkg20001/fluxgui-snap

But d-bus does not seem to work...

**Comment by elopio** [comment]
Hey @mkg20001. Please tell us about your problem and we might be able to help:
https://lists.ubuntu.com/mailman/listinfo/snapcraft

**Comment by DrMajkrosoft** [comment]
Also, I see that you are working on a new design for the v4 version. Do you think you can make something like for Ubuntu too? I mean, your app for Ubuntu still says "year 2010". 

![17799276_1291482254221854_843527567407768903_n](https://cloud.githubusercontent.com/assets/12301022/24667972/800cbb3c-1965-11e7-82a4-eb0cb8c0a80f.png)

**Comment by faraco** [comment]
flatpak package should be considered too.

**Comment by dietrichstats** [comment]
I think like @faraco , it may not be necessary to open a new ticket and direct this as a discussion. Currently Flatpak works better on the desktop and has a much [wider adoption](https://kamikazow.wordpress.com/2018/06/08/adoption-of-flatpak-vs-snap-2018-edition/) than Snap, which makes Flatpak the best option.

**Comment by michaelcyyuen** [comment]
This is the best thing I would love to have on my development machine.
I can't sleep without it!
