### ISSUE TITLE
Requirements file missing

### ISSUE THREAD

**Issue by ant6** [xflux-gui/fluxgui#55]
Hi,

using OpenSUSE 42.2 and installing from GitHub source. You mention (in README):
```
sudo python setup.py install --record installed.txt
```
But there is no such file. Also, maybe include required libs in `setup.py` itself?

I had to manually install:
```
pexpect
python-gconf
pyxdg
python-appindicator
```
to get `fluxgui` command to run without ImportErrors.

**Comment by ntc2** [comment]
You said

> But there's no such file.

What file?

**Comment by ant6** [comment]
Requirements file. Usually `requirements.txt`

**Comment by ntc2** [comment]
OK, I think I understand now: the `installed.txt` file is *created* by the `setup.py install --record installed.txt`: the `--record <filename>` option tells `setup.py` to record the names of all of the files it installed in `<filename>`. This makes it easy to uninstall with `xargs rm -vr < installed.txt`.

I don't know anything about "requirements files". Can you point to some documentation or explain why this is better than just listing the requirements in the README?

**Comment by ant6** [comment]
Yes, but running `pip freeze` also lists `f.lux-indicator-applet==1.1.10rc0` as installed and you could simply run `pip uninstall f.lux-indicator-applet` to get rid of it, no file tricks needed, I think. Most Python apps now use pip.

"requirements file" is more pythonic/easier way to manage dependencies: e.g. one should run `pip install -r requirements.txt` and that's it.
Official docs:
https://pip.pypa.io/en/stable/user_guide/#requirements-files

Or just modyfy setup.py a bit: https://packaging.python.org/requirements/

**Comment by ntc2** [comment]
Thanks for explaining. The `pip uninstall` sounds useful. Right now I use the Ubuntu package manager to install the dependencies. If using the `requirements.txt` for the install, I guess that would install separate copies of the dependencies using `pip`? If "yes", then I prefer manually installing the dependencies. But having a `requirements.txt` for people that want to install things that way might not hurt.

**Comment by faraco** [comment]
requirements.txt may help for the guys who like to install through that, and adding those in setup.py helps too.

However, some of the required dependencies are not available through pip (appindicator, glade, libxxf86vm1) and pygtk is just a wrapper to gtk2, which you still need to manually install with sudo apt (or rpm in case there is working package with right dependencies name).

**Comment by ntc2** [comment]
Based on @momozor 's comment I think this issue can be closed as it doesn't sound like there's much benefit to the `requirements.txt` file in our case.
