### ISSUE TITLE
Error: signal 'child-added' is invalid for instance '0x2a12320' of type 'GtkMenu'

### ISSUE THREAD

**Issue by Fl3xX** [xflux-gui/fluxgui#61]
I installed fluxgui on **Debian 8 Jessie (stable)**. It worked fine until i get this today : 
```
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2461: signal 'child-added' is invalid for instance '0x2a12320' of type 'GtkMenu'
self.indicator.set_menu(self.create_menu())
```
I'm not familiar with linux yet. Something to do with gtk or python ? Or path ? I need help. Thanks !

**Comment by ntc2** [comment]
Here's a shot in the dark: do you still have this problem if you restart
your computer? This might help, if you just updated glib.

On May 7, 2017 2:31 AM, "Fl3xX" <notifications@github.com> wrote:

Hi,

I installed fluxgui. It worked fine until i get this today :
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning:
/build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2461: signal
'child-added' is invalid for instance '0x2a12320' of type 'GtkMenu'
self.indicator.set_menu(self.create_menu())
I'm not familiar with linux yet. Something to do with gtk or python ? Or
path ? I need help. Thanks !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xflux-gui/xflux-gui/issues/61>, or mute the thread

**Comment by Fl3xX** [comment]
I just updated libc6 and libdbus-glib2.0-cil_0.6.0-1_all.deb, restarted and yet i have the exact same message :( and i can't run xflux :((

**Comment by ntc2** [comment]
You mention a `.deb` file, so I assume you're using Ubuntu or Debian. What Linux distribution and release are you using (e.g. I'm using Ubuntu 16.04)?

**Comment by Fl3xX** [comment]
I'm runing Debian 8 Jessie ( stable )

**Comment by ntc2** [comment]
Thanks for the info. I don't know how to debug this, so I'm just going to wait and see if anyone else experiences this problem. Sorry.

In the mean time, consider using [RedShift](https://wiki.archlinux.org/index.php/redshift) instead.

**Comment by Fl3xX** [comment]
Thanks, i'll keep looking and let you know if i find anything.

**Comment by adam-becker** [comment]
Same issue:

```
$ fluxgui
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-y6934K/glib2.0-2.42.1/./gobject/gsignal.c:2461: signal 'child-added' is invalid for instance '0x2ba62b0' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())
```

**Comment by iamjosejimenez** [comment]
Same here:

`/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-B1uXKV/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x55e5e340a3e0' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())
`
Running on debian 9. Already running on debian 8 but It broke after updating.

**Comment by smallmac933** [comment]
Bumping this, I'm running Debian 9 64 bit and after following the install instructions running fluxgui returns this:
```
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-B1uXKV/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x56017ee133e0' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())
```

On the first run after rebooting the GUI opens but doesn't actually change the screen warmth, any subsequent attempts to run the GUI open the tab in the bottom left, but it doesn't respond to any clicks.

Probably unrelated but previously I also got "Failed to load module "canberra-gtk-module"" until I installed that

**Comment by ntc2** [comment]
Hopefully this is a Gtk2 problem that will go away when @bil-elmoussaoui's work in #48 gets incorporated. :crossed_fingers:

**Comment by bil-elmoussaoui** [comment]
I don't know if it's a gtk2 issue. But i hope this will be fixed with the gtk3 version

**Comment by MattJones76** [comment]
Same issue running Debian 8.6

**Comment by CodaAmok** [comment]
Just jumped on 9.1 today on an x64 machine, used manual instructions and getting the same issue.

**Comment by ibovangeffen** [comment]
Having the same issue on Debian 9.2

**Comment by DeeToTheVee** [comment]
I'm having the same issue as the above. fluxgui loads but nothing can actually be changed.

$ fluxgui 
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:64: GtkWarning: Unable to locate theme engine in module_path: "adwaita",
  appindicator.CATEGORY_APPLICATION_STATUS)

/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-B1uXKV/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x5569c94837f0' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu()


OS: Debian 9
Kernel: 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

**Comment by scrudge** [comment]
```
~$ fluxgui 
/usr/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: 
   /build/glib2.0-B1uXKV/glib2.0-2.50.3/./gobject/gsignal.c:2523: 
   signal 'child-added' is invalid for instance '0x5650ec48b3e0' of 
   type 'GtkMenu' self.indicator.set_menu(self.create_menu())

~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.3 (stretch)
Release:	9.3
Codename:	stretch

```

**Comment by CyberJinh** [comment]
~$ fluxgui
/home/xxxx/.local/lib/python2.7/site-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-B1uXKV/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x56231ae693c0' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())

debian 9.3 stretch

**Comment by Narwhalish** [comment]
Bump. I'm also having this issue.

**Comment by agtig** [comment]
I have the same issue:
```
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-B1uXKV/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x55d02d88d3e0' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())
```
Had the same canberra issue as previously described in the thread. Installed it using sudo apt-get install libcanberra-gtk-module.

Running Debian 9.3 stretch

**Comment by pevans01** [comment]
I have the same issue:

`/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-B1uXKV/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x5643336fd400' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())`


This is after solving an issue with: 
`Gtk-Message: Failed to load module "canberra-gtk-module"`

On Debian 9.3

**Comment by mabt** [comment]
Same issue:

$ /usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-B1uXKV/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x563a2a31b0b0' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())

cat /etc/debian_version
9.4

**Comment by MarlonMrN** [comment]
same issue here. w/ debian 9.4

**Comment by g0g0lganesh** [comment]
Same problem w. Jessian 8 Stable

**Comment by v461m** [comment]
Only the first time i used it works, than the message is:

fluxgui
/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-B1uXKV/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x56100c122460' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())
OS: Debian 9.5 stretch
Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

**Comment by ntc2** [comment]
PR #112 just landed, and now `fluxgui` uses Python 3 and GTK+ 3. Please let me know if this issue still exists in the new version.
