### ISSUE TITLE
Slow resume from sleep

### ISSUE THREAD

**Issue by naisanza** [xflux-gui/fluxgui#66]
A quick test, using f.lux on a laptop causes logging in after resuming from sleep mode to take up to 10 or 15 seconds long.

Disabling f.lux, putting the system to sleep mode, and resuming, logs in immediately after authenticating

I only have one laptop running Ubuntu 16.10 to test this out right now, if anyone else is/has experienced this, please add the OS you're running f.lux under.

**Comment by ntc2** [comment]
Could you try disabling fluxgui, running the xflux command line program
manually (e.g. xflux -l 0 -g 0 -k 3400 -nofork), and seeing if you still
experience the delay? I want to determine if the GUI or xflux is to blame.
