### ISSUE TITLE
Feature request: application-specific brightness

### ISSUE THREAD

**Issue by webbp** [xflux-gui/fluxgui#70]
I use light-on-dark terminal, and when I switch to browser, the increase in luminance hurts my eyes. I made an Applescript on Mac to dim when I leave iTerm and brighten again when I return, but the latency sucks. It would be great if xflux and f.lux could change the brightness depending on the frontmost application/window, and with low latency. Nice to have: who cares about applications, just adjust the brightness continuously to keep the total luminance from the screen approximately the same.

**Comment by ntc2** [comment]
Measuring and adjusting brightness independent of applications sounds like a feature for `xflux` itself. The `fluxgui` is just a GUI that calls `xflux` internally to control the brightness.

Implementing application specific brightness in `fluxgui` might make sense. I'd be happy to look at a pull request for this feature.
