### ISSUE TITLE
[Enhancement] Different icon names for application / tray

### ISSUE THREAD

**Issue by varlesh** [xflux-gui/fluxgui#79]
Will be good use another name for tray icons. It's very good looking with monochrome icon themes.
For example:
```
lf.indicator.set_icon('fluxgui-panel')
```

**Comment by ntc2** [comment]
Sorry, I don't understand. Can you say more, or submit a pull request?

**Comment by varlesh** [comment]
xflux-gui used single icon for application and tray - it's not good looking with monochrome icon themes (on tray).
![image](https://user-images.githubusercontent.com/8083855/32401566-945add04-c12a-11e7-8205-618602ba2b4c.png)
I think better use for desktop-file icon `fluxgui`, but for tray `fluxgui-panel`

**Comment by varlesh** [comment]
need rename files to:
```
icons/ubuntu-mono-dark/fluxgui-panel.svg
icons/ubuntu-mono-light/fluxgui-panel.svg
```
and change code line:
```
lf.indicator.set_icon('fluxgui-panel')
```

**Comment by varlesh** [comment]
@ntc2 Unity use `-panel` prefix for tray icons. This worked even if specified original icon name for tray (for example qbittorrent, vlc and etc...) If available this icon (with prefix) on system icon theme  > this applied on Unity tray.
BUT this not worked for non-Unity DE's (KDE, XFCE and etc...) And now Unity dropped.
Solution - use another icon name for tray, it's worked for all DE's.

**Comment by ntc2** [comment]
Thanks for the PR, merged!
