### ISSUE TITLE
Applet icon is broken on latest build

### ISSUE THREAD

**Issue by c2c533c4f237** [xflux-gui/fluxgui#82]
Hi, I have installed this via the AUR: https://aur.archlinux.org/packages/xflux-gui-git/

I've installed it previously via AUR and I noticed that an icon did show up but I remember it not being as nice as when I used the deb - it was the square icon that's orange with a sun and blue, which seemed a little too large for the taskbar. I seem to remember that when I was using Linux Mint the icon looked closer to the other applet icons, maybe a circular sun or something like that without colors. I can't remember exactly but I do remember that the icon stood out as being too big on my last install.

Now on a new machine I've installed it again from AUR and the icon is broken, not even the overly large app icon, a square with a red x.

Is this a problem with the AUR package or the latest build?

**Comment by Kilian** [comment]
Can you share a screenshot? I might have something to do with https://github.com/xflux-gui/fluxgui/pull/80

**Comment by c2c533c4f237** [comment]
![screenshot](https://user-images.githubusercontent.com/124313/32483523-4ac61900-c351-11e7-93bc-ae879572b2f3.png)

The broken icon is the one in the middle.

**Comment by Kilian** [comment]
Thanks. If you start xflux-gui from the terminal, does it show any errors or other output?

**Comment by c2c533c4f237** [comment]
I only see this repeated 3 times

`(fluxgui:14482): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",`

**Comment by Kilian** [comment]
What I think happened is that with #80, we had a fallback to the fluxgui desktop icon. Now it's trying to search for fluxgui-panel and it can't find that. https://github.com/xflux-gui/fluxgui/blob/master/setup.py#L7 should also be renamed, or at least copied over, to fluxgui-panel.svg. @ntc2 what do you think?

**Comment by ntc2** [comment]
@Kilian , @c2c533c4f237 : I must admit that I didn't understand Issue #79 and the corresponding PR #80 very well, but tested that the change did not affect `fluxgui` for me by completely uninstalling my old `fluxgui` and then installing the new `fluxgui` patched with PR #80 and checking that the icon still worked. However, I realize now that I don't ever use the desktop icon, just the tray icon, so my test was probably inadequate. My desktop environment is `xmonad` + `gnome-panel` and I don't know where to see the desktop icon.

@c2c533c4f237 : I don't have any experience with Arch/AUR, but I notice that AUR package you linked says last updated 2017-09-25, before #80 was merged. But perhaps that just means the package metadata was updated then, but when you install the package you get the latest `HEAD` of `fluxgui`?

@varlesh , thoughts on this new issue and how it might relate to your #80 ?

I will make the change suggested by @Kilian and let's see if that helps @c2c533c4f237 ...

**Comment by Kilian** [comment]
@ntc2 I don't use Arch either but from my understanding, AUR builds directly from the git(hub) repo on install.

**Comment by ntc2** [comment]
@c2c533c4f237 : I pushed a version that renames the remaining, third icon as suggested by @Kilian . Can you try reinstalling and see if that helps? Also, a couple of things that I noticed

- I ended up with a broken tray icon after reinstalling and had to logout and login again (i.e. restart `gnome-panel`) before the tray icon worked, so let if it's still broken, let me know if logging out and back in helps.

- when doing a manual global install with `sudo python setup.py install` the `/usr/local/share/{icons,applications}` are only readable by root. This seems wrong, but is probably an existing problem. I usually install locally with `python setup.py install --user`, but tried to global install to see if the `fluxgui` icon would appear in my Applications menu (it did not).

**Comment by c2c533c4f237** [comment]
Thank you, this fix works great! I did not have to do anything special with the install as the AUR package took care of that. Apparently back when I saw the larger icon I thought it didn't look good but thought maybe that was supposed to be that way on non-ubuntu systems. So now I can rebuild it there too.
![newscreenshot](https://user-images.githubusercontent.com/124313/32501510-0ecbba90-c38d-11e7-841c-1c76c637ce0d.png)

**Comment by ntc2** [comment]
@c2c533c4f237 , thanks for testing the fix; @Kilian thanks for figuring out what the problem was.

**Comment by Kilian** [comment]
Thanks for the quick fix Nathan! High-fives all round :)

**Comment by c2c533c4f237** [comment]
Hi, I have noticed that the icon is reverting back to the broken icon after a while of being open, not sure what is triggering that.

**Comment by ntc2** [comment]
Hmm, that is very strange! I would expect that either it works or it doesn't.

**Comment by c2c533c4f237** [comment]
Yeah, I'm not sure either...I just restarted it again in the command window to see if I see anything come up.

**Comment by varlesh** [comment]
@c2c533c4f237 Install ubuntu-mono icon theme and apply.

**Comment by varlesh** [comment]
@ntc2 This indicator use `ubuntu-mono` icons for tray and i think will be better add this package as depend on readme and PKGBUILD. It's Arch problem...

**Comment by varlesh** [comment]
@ntc2 I can add icons for Breeze (KDE), elementary and Adwaita (Gnome) if needed. It's will be completed on mostly popular DE

**Comment by varlesh** [comment]
For example:
![image](https://user-images.githubusercontent.com/8083855/32688363-c78ae93a-c6e8-11e7-8ea9-5f231c561f2e.png)

**Comment by c2c533c4f237** [comment]
To clarify the fix that was pushed did show the icon as I had in my screenshot, the yellow and blue one. However I believe after a Window Manager crash it reverted back to that broken icon. I have not had this problem since as my WM hasn't crashed. Is there some fallback code somewhere that restores the default icon from the different distros (which my distro doesn't have) instead of the yellow and blue one?

I will try installing the ubuntu icons though, thanks.

**Comment by ntc2** [comment]
@varlesh , thanks for the additional icons! Can you explain why installing `ubuntu-mono` would help? I thought `fluxgui` shipped with its own icons? I'm using Ubuntu and do have `ubuntu-mono` installed, but I thought that was just to get the dark theme that I'm using for `gnome-panel`. But it should be obvious by now that I don't understand how icons work :)

@c2c533c4f237 , I just merged another PR from @varlesh. Please try installing the icon themes he suggests and installing the updated version.

**Comment by c2c533c4f237** [comment]
Ah ha! Thank you. After rebuilding I'm seeing a themed icon like in the image above, like the adwaita.svg . This does go better with my tray icons which are also similar so thanks! I still am not sure why it reverted before or if it was from my WM crashing but if it's relying on those external themes now maybe that won't be so. Thanks again.

**Comment by varlesh** [comment]
@c2c533c4f237 I don't know why your WM crashed... it's only SVG icon.

**Comment by c2c533c4f237** [comment]
So it happened again and I don't think it is related to my WM crashing - I remember all the times I did that I was recompiling wine. Only that one icon is affected though.

**Comment by sicherist** [comment]
Only a minor issue but I thought, i'd let you know: Since one of the latest updates the fluxgui tray icon is hardly visible any more on KDE breeze dark. If I hover with the cursor it becomes better. It looks like if "breeze.svg" was used instead of "breeze-dark.svg".

![screenshot_20171222_162350](https://user-images.githubusercontent.com/6120865/34303404-6bcc1ef8-e735-11e7-8c96-2e413d0f77ec.png)
![screenshot_20171222_162730](https://user-images.githubusercontent.com/6120865/34303409-6f4e9394-e735-11e7-9162-81c2b2b50c8a.png)

**Comment by varlesh** [comment]
@sicherist breeze-dark available:
https://github.com/xflux-gui/fluxgui/blob/master/icons/breeze-dark/status/22/fluxgui-panel.svg

**Comment by sicherist** [comment]
Thank you for your reply. I already have this exact file in "/usr/share/icons/**breeze-dark**/status/22/"
but it seems that it isn't used when I activate "breeze-dark"-theme. Instead the file from the breeze (non-dark) directory is used in (/usr/share/icons/**breeze**/status/22/fluxgui-panel.svg)

I have no idea why this is, but if I can even delete "/usr/share/icons/**breeze-dark**/status/22/fluxgui-panel.svg" and it doesn't change anything. If I however edit "/usr/share/icons/**breeze**/status/22/fluxgui-panel.svg" for example to a different color, it is applied to both breeze and breeze-dark.

**Comment by varlesh** [comment]
@sicherist I try add CSS for icons. You can check this:
https://github.com/xflux-gui/fluxgui/pull/87

**Comment by varlesh** [comment]
also not forgot clear icon cache and reapply icon theme:
`rm -rf ~/.cache/icon*`

**Comment by ntc2** [comment]
@sicherist : I merged PR #87, please try updating and see if it fixes your problem.

@varlesh : thanks!

**Comment by sicherist** [comment]
Thank you! Deleting the icon-cache didn't do the trick but after the latest fluxgui update the icon looks alright in breeze-dark. :)

**Comment by rahmatfajar15** [comment]
Can you add the icon for vertex-maia-dark too please?
I'm using manjaro XFCE version
Thanks

**Comment by AdamSLevy** [comment]
I am using Arch Linux and i3wm. I just installed xflux-gui-git from the AUR and ran into this issue. I have /usr/share/icons/breeze-dark/status/22/fluxgui-panel.svg present on my system. Not sure how to trouble shoot this further. I have restarted it many times from both a systemd user service (how I have it running on my previous system) and manually from the command line.

**Comment by ntc2** [comment]
No action on this issue for a long time, and the PR #112 porting `fluxgui` to Python 3 and GTK+ 3 just landed, so I'll hope this is fixed now, but let me know if it's not.
