### ISSUE TITLE
Prevents running xcalib -i -a

### ISSUE THREAD

**Issue by Belalseman** [xflux-gui/fluxgui#84]
I use a script that runs "xcalib -i -a" to invert my colours when I need to (for vision impairment reasons), and running fluxgui seems to stop this from working. I've gotten around this by getting my script to kill fluxgui and then start it again when I am done inverting colours. 

The problem is that this seems to necessitate a sleep of a whole second after fluxgui has quit to make sure xcalib actually works, and as I invert colours back and forth a lot throughout the day, the delay is driving me bonkers.

Can something be done about the xcalib problem?

**Comment by ntc2** [comment]
This sounds like an issue with `xflux`, the program that `fluxgui` uses to control the screen color. You could try reporting your issue upstream to `xflux`. Another option is to try `redshift`.
