### ISSUE TITLE
[Enhancement] Update main logo and ubuntu-mono icons

### ISSUE THREAD

**Issue by varlesh** [xflux-gui/fluxgui#85]
I draw icon as ubuntu style.... if you like i can create PR :) 

![image](https://user-images.githubusercontent.com/8083855/32697188-d24875d8-c7a4-11e7-9c87-09b4aaa7b4f6.png)

**Comment by varlesh** [comment]
For compare:
![image](https://user-images.githubusercontent.com/8083855/32697211-3c4b807e-c7a5-11e7-8051-b3d6984b0973.png)

**Comment by ntc2** [comment]
Yes, PR would be great!

**Comment by ntc2** [comment]
PR merged, thanks!
