### ISSUE TITLE
DisplayLink Supported on Linux? 

### ISSUE THREAD

**Issue by APeppyPlatypus** [xflux-gui/fluxgui#91]
Hello,

As noted in title, doesn't look like DisplayLink is supported on Linux?

Have flux installed on Windows 10 and on Ubuntu 16.04.3 LTS and using USB Docking station with DisplayLink. Windows 10 works fine/see notes about it being supported for Windows 10 but don't see anything for Linux and DisplayLink for flux/doesn't work on Ubuntu. 

Have a side monitor directly connected to Ubuntu machine and see that the filter is being applied there and not on the DisplayLink monitor. 

There was a suggestion to use redshift instead if having issues, but looks like that doesn't support DisplayLink as well and am seeing the same from trying that.

Note that I tried from PPA and also manual install with latest. 

Can provide whatever else need but doesn't sound like has been looked at/anyone has had an issue with it before, so probably just never implemented for Linux?

**Comment by ntc2** [comment]
Hi @APeppyPlatypus , unfortunately, the the open source `fluxgui` project does not develop the closed source `xflux` program that is used behind the scenes to control the screen brightness. You could report your issue with `xflux`:  https://forum.justgetflux.com/category/7/linux.

Good luck!
