### ISSUE TITLE
Installed on Ubuntu 1404, It doesn't adjust anything

### ISSUE THREAD

**Issue by jardayn** [xflux-gui/fluxgui#92]
Installed FluxGui via PPA and then compiled from source. Followed the guide perfectly.

In both cases it won't work. At all. The screen color does not get changed.. I tried pausing/restarting/previewing . Nothing works.

**Comment by hgontijo** [comment]
I'm having the same issue on Ubuntu 17.10 by installing with PPA. Maybe it require elevation? I couldn't find anything on the system logs.

**Comment by monspid** [comment]
The same issue on `Linux Mint 18.2 Sonya`.

**Comment by murraay** [comment]
Same issue on 18.3 Linux Mint Sylvia

**Comment by dalbinaco** [comment]
Same on elementaryOS Loki

**Comment by ajeetdsouza** [comment]
I have the same issue on (Xubuntu 17.10).

**Comment by ntc2** [comment]
Assuming this is #27.
