### ISSUE TITLE
fluxgui applet closes before it's usable

### ISSUE THREAD

**Issue by humblepi-ipelbmuh** [xflux-gui/fluxgui#93]
Hi, I'm a beginner running raspbian on a raspberry pi zero w.

Whenever I boot the pi, the flux applet starts, shows this message:
 
_The f.lux indicator applet needs to know your latitude or zipcode to run. Please fill either of them in on the preferences screen and click 'Close'._

...when I close the message the applet shuts down.
I investigated this issue by running this command in terminal:

_fluxgui help_

...that command brought these results:

**/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py:71: Warning: /build/glib2.0-F5w919/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x817118' of type 'GtkMenu'
  self.indicator.set_menu(self.create_menu())
[Errno 8] Exec format error
Critical error. Exiting.
Traceback (most recent call last):
  File "/usr/local/bin/fluxgui", line 20, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 213, in main
    app = FluxGUI()
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 28, in __init__
    self.exit(1)
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxapp.py", line 46, in exit
    gtk.main_quit()
RuntimeError: called outside of a mainloop**

Please help me resolve this issue. 
HP

**Comment by pbojinov** [comment]
Seeing the same issue as well. On Raspberry Pi 3 running Raspbian 9.1

**Comment by molly78** [comment]
same on Ubuntu 16.04 on an Odroid XU4

**Comment by rigg77** [comment]
Ditto. RasPi 3, Raspbian

**Comment by faraco** [comment]
Hi.

`[Errno 8] Exec format error`

Probably wrong binary architecture? Possibly referring to `xflux` binary or a file that wasn't set as an executable?

@humblepi-ipelbmuh @kundaria

Also, do you guys mind to share your downloaded xflux binary and system architecture with:

```bash
file $(which xflux); lscpu
```

**Comment by dutchybeatz** [comment]
same on raspberry p3

**Comment by dutchybeatz** [comment]
same on raspberry p3

**Comment by ntc2** [comment]
I just merged PR #112 which ports fluxgui to GTK+ 3. Please let me know if this issue persists with the new version.
