### ISSUE TITLE
CentOS 7   can not run succesfull!

### ISSUE THREAD

**Issue by maxwellhouse102** [xflux-gui/fluxgui#99]
install on CentOS 7 follow Install Instructions in Code page.
but can not work.
messages below .   
is anyone knows how to resolve?
is someother apps function same can instead fluxgui?

[root@bogon fluxgui]# fluxgui
Traceback (most recent call last):
  File "/usr/bin/fluxgui", line 17, in <module>
    from fluxgui.fluxapp import main
  File "/usr/lib/python2.7/site-packages/fluxgui/fluxapp.py", line 3, in <module>
    from fluxgui import fluxcontroller, settings
  File "/usr/lib/python2.7/site-packages/fluxgui/fluxcontroller.py", line 1, in <module>
    from fluxgui import xfluxcontroller
  File "/usr/lib/python2.7/site-packages/fluxgui/xfluxcontroller.py", line 1, in <module>
    import pexpect
ImportError: No module named pexpect

**Comment by ntc2** [comment]
Sounds like you didn't install `pexpect`. Are you sure you did
```
sudo yum install git python-appindicator python2-pyxdg python2-pexpect gnome-python2-gconf pygtk2 pygtk2-libglade
```
? In particular, the `sudo yum install python2-pexpect` part?

**Comment by maxwellhouse102** [comment]
there is no python2-pexpect package.
so. how can i get it ?

[root@bogon ssdt]# yum install python2-pexpect
已加载插件：fastestmirror, langpacks
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Repository centosplus is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: mirrors.163.com
 * extras: mirrors.163.com
 * nux-dextop: mirror.li.nux.ro
 * updates: mirrors.163.com
没有可用软件包 python2-pexpect。
错误：无须任何处理

**Comment by ntc2** [comment]
Ok, then Cent OS install instructions are wrong. A little googling tells me the package might be called `pexpect` on Cent OS, but I'm not using Cent OS so I can't check myself.

How about you figure out what the dependency packages are called on Cent OS and reply with that information here?

**Comment by maxwellhouse102** [comment]
right .  install pexpect is correct.
now fluxgui had installed. and can be runing the gui interface. 
but it not work well. 
i have set the other color.  
but it not display warmer.  the color has not change .
donot know where is wrong....

fluxgui on Windows is work well and is so cool.
What a pity not support Centos.
